export const dummyQuestions = [
  {
    postId: 0,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 1,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 2,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 3,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 4,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 5,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 6,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 7,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 8,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 9,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 10,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 11,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 12,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 13,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 14,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 15,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 16,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 17,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 18,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 19,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 20,
    votes: 0,
    answers: 3,
    views: 3,
    title: "20번째 질문",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 21,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 22,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 23,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 24,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 25,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 26,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 27,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 28,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
  {
    postId: 29,
    votes: 0,
    answers: 3,
    views: 3,
    title: "A class pointer does not name a type",
    body: 'I have 3 C++ files: Main.cpp #include "FileA.h" FileA.h #include "FileB.h" class FileA{ private: FileB* b; }; FileB.h class FileB{ private: FileA* A; ...',
    photoURL: "https://i.stack.imgur.com/56OT9.jpg?s=32&g=1",
    nickName: "Kyle G",
    createdAt: "2 mins ago",
  },
];
