export const DummyTags = [
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 2441121,
    name: "javascript",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 2050053,
    name: "python",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1872553,
    name: "java",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1565695,
    name: "c#",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1448762,
    name: "php",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1390132,
    name: "android",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1151397,
    name: "html",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1030558,
    name: "jquery",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 780318,
    name: "c++",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 775732,
    name: "css",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 676238,
    name: "ios",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 653331,
    name: "mysql",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 646858,
    name: "sql",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 469005,
    name: "r",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 446680,
    name: "node.js",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 423870,
    name: "reactjs",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 401405,
    name: "arrays",
  },
];
