export const DummyTags = [
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 2441137,
    name: "javascript",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 2050099,
    name: "python",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1872567,
    name: "java",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1565705,
    name: "c#",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1448770,
    name: "php",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1390138,
    name: "android",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1151410,
    name: "html",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 1030559,
    name: "jquery",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 780325,
    name: "c++",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 775739,
    name: "css",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 676238,
    name: "ios",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 653334,
    name: "mysql",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 646866,
    name: "sql",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 469007,
    name: "r",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 446687,
    name: "node.js",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 423883,
    name: "reactjs",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 401406,
    name: "arrays",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 387753,
    name: "c",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 370728,
    name: "asp.net",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 348355,
    name: "json",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 334747,
    name: "ruby-on-rails",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 326105,
    name: "python-3.x",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 324899,
    name: ".net",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 324210,
    name: "sql-server",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 320454,
    name: "swift",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 299349,
    name: "django",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 292549,
    name: "objective-c",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 286285,
    name: "angular",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 271303,
    name: "excel",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 263962,
    name: "pandas",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 262585,
    name: "angularjs",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 254068,
    name: "regex",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 226174,
    name: "ruby",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 221526,
    name: "iphone",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 220892,
    name: "ajax",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 220551,
    name: "linux",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 210739,
    name: "xml",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 204467,
    name: "vba",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 201347,
    name: "spring",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 199383,
    name: "laravel",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 199299,
    name: "asp.net-mvc",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 198886,
    name: "typescript",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 190074,
    name: "database",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 187334,
    name: "wordpress",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 178930,
    name: "string",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 167982,
    name: "mongodb",
  },
  {
    has_synonyms: false,
    is_moderator_only: false,
    is_required: false,
    count: 166986,
    name: "wpf",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 161668,
    name: "postgresql",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 160739,
    name: "windows",
  },
  {
    has_synonyms: true,
    is_moderator_only: false,
    is_required: false,
    count: 156891,
    name: "xcode",
  },
];
